version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 201
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 400
      runas: root
