version: 0.1
os: linux
hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 205
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 401
      runas: root
